# Name of the workflow
name: Python version
  # Set in the trigger policy
  # In this case the workflow is executed on a `push` event,
  # or when a new commit commit is pushed to the repository
on: [push]
  # List of steps to be executed by the workflow
jobs:
  # Set the name of the job
  check-python-version:
    # configuring the operating system the workflow should run on
    # In this case, the job on ubuntu
    runs-on: ubuntu-latest
    steps:
      ## Use public checkout action in version v2
      ## to checkout the existing code in the repository
      - uses: actions/checkout@v2
      ## Use the public `setup-python` action  in version v2  
      ## to install python on the  Ubuntu based environment 
      - uses: actions/setup-python@v2
        ## executes the `python --version` command
      - run: python --version     
  

